"""
Letters & Documents catalog for DERB MOBILE.

This module is the single source of truth for "what letters and documents
exist". The landing page, the dynamic forms, the document composer and the
exporters all read from here - so adding a new document type later means
adding ONE entry to DOC_TYPES below. Nothing else changes.

    CATALOG  ->  FORM FIELDS  ->  COMPOSED DOCUMENT  ->  PREVIEW / PDF / DOCX

Document kinds
--------------
letter       prose document (Dear ... / Yours faithfully)
agreement    structured parties/clauses/execution document
declaration  first-person sworn-style statement

Re-usable field groups keep the catalog small: a group is instantiated with a
role label and a prefix, e.g. "person:Seller:seller" produces seller_full_name,
seller_address, ... and prints under the heading "Seller".
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Field definitions shared by groups
# ---------------------------------------------------------------------------
FIELD_DEFS: dict[str, dict[str, str]] = {
    "full_name": {"label": "Full Name", "type": "text"},
    "employee_name": {"label": "Employee Full Name", "type": "text"},
    "address": {"label": "Address", "type": "text"},
    "phone": {"label": "Phone Number", "type": "tel"},
    "id_details": {"label": "ID / Identification Details", "type": "text",
                   "placeholder": "e.g. NIN, driver's licence or voter's card number"},
    "email": {"label": "Email", "type": "email"},
    "document_date": {"label": "Date of Document", "type": "date"},
    "recipient_name": {"label": "Recipient Name", "type": "text"},
    "recipient_title": {"label": "Recipient Title / Role", "type": "text"},
    "organisation": {"label": "Organisation / Company", "type": "text"},
    "recipient_address": {"label": "Recipient Address", "type": "text"},
    "company_name": {"label": "Company / Organisation", "type": "text"},
    "position": {"label": "Position / Role", "type": "text"},
    "start_date": {"label": "Start Date", "type": "date"},
    "end_date": {"label": "End Date", "type": "date"},
    "date_issued": {"label": "Date", "type": "date"},
    "qualifications": {"label": "Qualifications", "type": "textarea",
                       "placeholder": "Degrees, certificates, years of study"},
    "experience": {"label": "Relevant Experience", "type": "textarea"},
    "message": {"label": "Additional Message", "type": "textarea"},
    "reason": {"label": "Reason (optional)", "type": "textarea"},
    "make": {"label": "Make", "type": "text", "placeholder": "e.g. Bajaj"},
    "model": {"label": "Model", "type": "text"},
    "year": {"label": "Year", "type": "text", "inputmode": "numeric"},
    "colour": {"label": "Colour", "type": "text"},
    "reg_number": {"label": "Registration Number", "type": "text"},
    "chassis_number": {"label": "Chassis / VIN Number", "type": "text"},
    "engine_number": {"label": "Engine Number", "type": "text"},
    "asset_description": {"label": "Asset / Item Description", "type": "textarea"},
    "asset_location": {"label": "Asset Location", "type": "text"},
    "serial_number": {"label": "Serial Number (if any)", "type": "text"},
    "property_description": {"label": "Property Description", "type": "textarea"},
    "property_location": {"label": "Property Location", "type": "text"},
    "title_deed_number": {"label": "Title Deed / Document Number", "type": "text"},
    "sale_price": {"label": "Sale Price", "type": "text", "inputmode": "decimal",
                   "placeholder": "e.g. N450,000"},
    "amount_paid": {"label": "Amount Already Paid", "type": "text", "inputmode": "decimal"},
    "balance": {"label": "Outstanding Balance", "type": "text", "inputmode": "decimal"},
    "payment_method": {"label": "Payment Method", "type": "text",
                       "placeholder": "e.g. bank transfer, cash"},
    "date_of_sale": {"label": "Date of Sale", "type": "date"},
    "handover_date": {"label": "Handover Date", "type": "date"},
    "total_amount": {"label": "Total Amount", "type": "text", "inputmode": "decimal"},
    "installment_amount": {"label": "Installment Amount", "type": "text",
                           "inputmode": "decimal"},
    "installment_dates": {"label": "Payment Dates / Frequency", "type": "text",
                          "placeholder": "e.g. 30th of every month"},
    "final_payment_date": {"label": "Final Payment Date", "type": "date"},
    "loan_amount": {"label": "Loan Amount", "type": "text", "inputmode": "decimal"},
    "interest_rate": {"label": "Interest / Terms", "type": "text",
                      "placeholder": "e.g. 5% per month or interest-free"},
    "repayment_period": {"label": "Repayment Period", "type": "text",
                         "placeholder": "e.g. 6 months"},
    "repayment_start": {"label": "Repayment Start Date", "type": "date"},
    "resignation_date": {"label": "Resignation Date", "type": "date"},
    "last_working_day": {"label": "Last Working Day", "type": "date"},
    "authorized_person": {"label": "Authorized Person (Full Name)", "type": "text"},
    "authorized_person_id": {"label": "Authorized Person ID Details", "type": "text"},
    "purpose": {"label": "Purpose of Authorization", "type": "text"},
    "specific_action": {"label": "Specific Action Authorized", "type": "textarea"},
    "valid_until": {"label": "Valid Until / Expiry (if applicable)", "type": "date"},
    "current_owner": {"label": "Current Owner (Full Name)", "type": "text"},
    "new_owner": {"label": "New Owner (Full Name)", "type": "text"},
    "registration_number": {"label": "Registration / Document Number", "type": "text"},
    "reason_for_transfer": {"label": "Reason for Transfer", "type": "text"},
    "transfer_date": {"label": "Transfer Date", "type": "date"},
    "supporting_info": {"label": "Supporting Information", "type": "textarea"},
    "person_consenting": {"label": "Person Giving Consent", "type": "text"},
    "activity_or_purpose": {"label": "Activity / Purpose", "type": "text"},
    "dates_or_duration": {"label": "Date(s) / Duration", "type": "text"},
    "student_name": {"label": "Student Full Name", "type": "text"},
    "school_name": {"label": "School / Institution", "type": "text"},
    "class_or_level": {"label": "Class / Level", "type": "text"},
    "academic_session": {"label": "Academic Session", "type": "text",
                         "placeholder": "e.g. 2025/2026"},
    "institution_name": {"label": "Institution", "type": "text"},
    "programme": {"label": "Programme / Course", "type": "text"},
    "additional_terms": {"label": "Additional Terms / Conditions / Notes",
                         "type": "textarea"},
    "witness_1": {"label": "Witness 1 (Full Name)", "type": "text"},
    "witness_2": {"label": "Witness 2 (Full Name)", "type": "text"},
}

# ---------------------------------------------------------------------------
# Field groups. A doc def references a group as "key:RoleLabel:prefix";
# with no prefix the field names are used bare (single-instance groups).
# ---------------------------------------------------------------------------
GROUP_FIELDS: dict[str, list[str]] = {
    "person": ["full_name", "address", "phone", "id_details"],
    "contact": ["full_name", "phone", "email", "address"],
    "recipient": ["recipient_name", "recipient_title", "organisation",
                  "recipient_address"],
    "job_target": ["company_name", "position"],
    "application_body": ["qualifications", "experience", "message"],
    "vehicle": ["make", "model", "year", "colour", "reg_number", "chassis_number",
                "engine_number"],
    "asset": ["asset_description", "asset_location", "serial_number"],
    "property": ["property_description", "property_location", "title_deed_number"],
    "sale": ["sale_price", "amount_paid", "balance", "payment_method",
             "date_of_sale", "handover_date"],
    "payment_plan": ["total_amount", "amount_paid", "balance", "installment_amount",
                     "installment_dates", "final_payment_date"],
    "loan": ["loan_amount", "interest_rate", "repayment_period", "repayment_start"],
    "employment": ["employee_name", "company_name", "position", "start_date"],
    "resignation": ["company_name", "position", "resignation_date",
                    "last_working_day", "reason", "message"],
    "authorization": ["authorized_person", "authorized_person_id", "purpose",
                      "specific_action", "valid_until", "date_issued"],
    "transfer": ["current_owner", "new_owner", "asset_description",
                 "registration_number", "reason_for_transfer", "transfer_date",
                 "supporting_info"],
    "consent": ["person_consenting", "activity_or_purpose", "dates_or_duration"],
    "school": ["student_name", "school_name", "class_or_level", "academic_session"],
    "admission": ["institution_name", "programme", "academic_session"],
    "message": ["message"],
    "notes": ["additional_terms"],
    "witnesses": ["witness_1", "witness_2"],
    "document_date": ["document_date"],
}

LEGAL_DISCLAIMER = (
    "This document is a ready-to-use template prepared from the information you "
    "provided. It is not legal advice and does not by itself make the document "
    "legally valid. Where required, have it reviewed, stamped or notarised by a "
    "lawyer, notary public or the appropriate authority before use."
)

# ---------------------------------------------------------------------------
# Categories
# ---------------------------------------------------------------------------
CATEGORIES: list[dict[str, str]] = [
    {"slug": "business", "name": "Business & Official", "icon": "business",
     "blurb": "Formal letters for offices, clients and organisations."},
    {"slug": "agreements", "name": "Agreements & Contracts", "icon": "handshake",
     "blurb": "Written agreements that record what both parties agreed."},
    {"slug": "ownership", "name": "Ownership & Transfer", "icon": "transfer",
     "blurb": "Sale, handover and change-of-ownership documents."},
    {"slug": "employment", "name": "Employment & Workplace", "icon": "letter",
     "blurb": "Offer, appointment, resignation and HR letters."},
    {"slug": "legal", "name": "Legal / Declaration / Authorization", "icon": "document",
     "blurb": "Declarations, consents and authorizations. Formal layout."},
    {"slug": "school", "name": "School & Academic", "icon": "school",
     "blurb": "Admission, transfer and scholarship letters."},
    {"slug": "personal", "name": "Personal & General", "icon": "letter",
     "blurb": "Thank-you, condolence, invitation and everyday letters."},
]

CATEGORIES_BY_SLUG = {c["slug"]: c for c in CATEGORIES}


def _d(slug: str, name: str, category: str, desc: str, kind: str,
       groups: list[str], opening: str = "", closing: str = "",
       salutation: str = "Dear Sir/Madam", *, legal: bool = False,
       sign_roles: list[str] | None = None, keywords: str = "") -> dict[str, Any]:
    return {
        "slug": slug,
        "name": name,
        "category": category,
        "desc": desc,
        "kind": kind,
        "groups": groups,
        "opening": opening,
        "closing": closing,
        "salutation": salutation,
        "legal": legal,
        "sign_roles": sign_roles or [],
        "keywords": keywords.lower(),
    }


# ---------------------------------------------------------------------------
# Document types. Adding one entry here adds it to search, categories, forms,
# preview, PDF and DOCX automatically.
# ---------------------------------------------------------------------------
DOC_TYPES: list[dict[str, Any]] = [
    # ------------------------------------------------  BUSINESS & OFFICIAL
    _d("business-letter", "Business Letter", "business",
       "A formal letter from one business to another party.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "I am writing on behalf of our organisation regarding the matter below.",
       "Yours faithfully,"),
    _d("official-letter", "Official Letter", "business",
       "An official communication on behalf of an office or organisation.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "This is to formally bring the following matter to your attention.",
       "Yours faithfully,"),
    _d("formal-letter", "Formal Letter", "business",
       "A general formal letter for any serious correspondence.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "I write with respect to the subject matter stated above.",
       "Yours faithfully,"),
    _d("application-letter", "Application Letter", "business",
       "Apply formally for a position, opportunity or programme.",
       "letter",
       ["contact:Applicant:", "job_target::", "application_body::"],
       "I am writing to apply for the position of {position} at {company_name}.",
       "Yours faithfully,", "Dear Hiring Manager", keywords="job work apply"),
    _d("cover-letter", "Cover Letter", "business",
       "Introduce yourself alongside a CV or application.",
       "letter",
       ["contact:Applicant:", "job_target::", "application_body::"],
       "Please accept this letter as a cover for my application for the "
       "position of {position} at {company_name}.",
       "Yours sincerely,", "Dear Hiring Manager", keywords="job work cv"),
    _d("introduction-letter", "Introduction Letter", "business",
       "Introduce a person or business to a new contact.",
       "letter",
       ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "We are pleased to introduce the party described below to your office.",
       "Yours faithfully,"),
    _d("request-letter", "Request Letter", "business",
       "Request something formally - information, approval or assistance.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "I am writing to formally request the following.",
       "Yours faithfully,"),
    _d("enquiry-letter", "Enquiry Letter", "business",
       "Ask about products, services or information.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "I wish to make the following enquiries.",
       "Yours faithfully,", keywords="inquiry"),
    _d("complaint-letter", "Complaint Letter", "business",
       "Lodge a formal complaint about a product, service or conduct.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "I wish to formally register a complaint regarding the matter below.",
       "Yours faithfully,"),
    _d("response-letter", "Response Letter", "business",
       "Reply formally to a letter, complaint or request.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "Thank you for your correspondence. We respond as follows.",
       "Yours faithfully,", keywords="reply"),
    _d("invitation-letter", "Invitation Letter", "business",
       "Invite a guest, partner or official to an event.",
       "letter",
       ["contact:Host:", "recipient:Guest:", "message:Event Details:"],
       "We are pleased to invite you as detailed below.",
       "Yours faithfully,"),
    _d("recommendation-letter-business", "Recommendation Letter", "business",
       "Recommend a person or business for an opportunity.",
       "letter",
       ["contact:Referee:", "recipient:Recipient:", "message:Recommendation:"],
       "I write to recommend the person described below without reservation.",
       "Yours faithfully,", keywords="reference"),
    _d("reference-letter", "Reference Letter", "business",
       "Provide a factual character or work reference.",
       "letter",
       ["contact:Referee:", "recipient:Recipient:", "message:Reference Details:"],
       "This letter serves as a reference for the person described below.",
       "Yours faithfully,", keywords="recommendation"),
    _d("appreciation-letter", "Appreciation Letter", "business",
       "Thank a client, partner or staff member formally.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "On behalf of our organisation, we express our sincere appreciation.",
       "Yours faithfully,", keywords="thank you gratitude"),

    # --------------------------------------------  AGREEMENTS & CONTRACTS
    _d("general-agreement", "General Agreement", "agreements",
       "Record a simple agreement between two parties.",
       "agreement",
       ["person:First Party:first_party", "person:Second Party:second_party",
        "message:Terms of the Agreement:", "witnesses::", "document_date::"],
       sign_roles=["First Party", "Second Party"], legal=True),
    _d("sales-agreement", "Sales Agreement", "agreements",
       "Agreement for the sale of goods or an item.",
       "agreement",
       ["person:Seller:seller", "person:Buyer:buyer", "asset::", "sale::",
        "notes::", "witnesses::", "document_date::"],
       sign_roles=["Seller", "Buyer"], legal=True),
    _d("purchase-agreement", "Purchase Agreement", "agreements",
       "Agreement for the purchase of goods or property.",
       "agreement",
       ["person:Seller:seller", "person:Buyer:buyer", "asset::", "sale::",
        "notes::", "witnesses::", "document_date::"],
       sign_roles=["Seller", "Buyer"], legal=True),
    _d("payment-agreement", "Payment Agreement", "agreements",
       "Record a payment plan between creditor and debtor.",
       "agreement",
       ["person:Creditor:creditor", "person:Debtor:debtor", "payment_plan::",
        "notes::", "witnesses::", "document_date::"],
       sign_roles=["Creditor", "Debtor"], legal=True,
       keywords="payment plan debt owe"),
    _d("loan-agreement", "Loan Agreement", "agreements",
       "Document a loan, its terms and repayment plan.",
       "agreement",
       ["person:Lender:lender", "person:Borrower:borrower", "loan::",
        "notes::", "witnesses::", "document_date::"],
       sign_roles=["Lender", "Borrower"], legal=True),
    _d("debt-acknowledgement", "Debt Acknowledgement", "agreements",
       "Debtor formally acknowledges a debt and promise to pay.",
       "declaration",
       ["person:Debtor:debtor", "person:Creditor:creditor", "payment_plan::",
        "notes::", "witnesses::", "document_date::"],
       opening="I, {debtor_full_name}, hereby acknowledge that I am indebted to "
               "{creditor_full_name} in the sum and manner stated below, and I "
               "undertake to repay it in full.",
       sign_roles=["Debtor"], legal=True),
    _d("installment-payment-agreement", "Installment Payment Agreement", "agreements",
       "Agree repayments in fixed installments over time.",
       "agreement",
       ["person:Creditor:creditor", "person:Debtor:debtor", "payment_plan::",
        "notes::", "witnesses::", "document_date::"],
       sign_roles=["Creditor", "Debtor"], legal=True, keywords="installment"),
    _d("contract-agreement", "Contract Agreement", "agreements",
       "A general contract between two parties.",
       "agreement",
       ["person:First Party:first_party", "person:Second Party:second_party",
        "message:Contract Terms:", "witnesses::", "document_date::"],
       sign_roles=["First Party", "Second Party"], legal=True),
    _d("partnership-agreement", "Partnership Agreement", "agreements",
       "Record the terms of a business partnership.",
       "agreement",
       ["person:First Partner:first_partner", "person:Second Partner:second_partner",
        "message:Partnership Terms:", "witnesses::", "document_date::"],
       sign_roles=["First Partner", "Second Partner"], legal=True),
    _d("service-agreement", "Service Agreement", "agreements",
       "Agreement for services to be rendered and payment for them.",
       "agreement",
       ["person:Service Provider:provider", "person:Client:client",
        "message:Scope & Terms:", "witnesses::", "document_date::"],
       sign_roles=["Service Provider", "Client"], legal=True),
    _d("rental-agreement", "Rental Agreement", "agreements",
       "Agreement for renting a room, shop, apartment or item.",
       "agreement",
       ["person:Landlord / Owner:landlord", "person:Tenant / Renter:tenant",
        "asset:Property / Item Rented:", "payment_plan:Rent Terms:",
        "notes::", "witnesses::", "document_date::"],
       sign_roles=["Landlord / Owner", "Tenant / Renter"], legal=True),
    _d("handover-agreement", "Handover Agreement", "agreements",
       "Record the handover of duties, property or an office.",
       "agreement",
       ["person:Handing Over:handover_from", "person:Receiving:handover_to",
        "asset::", "notes::", "witnesses::", "document_date::"],
       sign_roles=["Handing Over", "Receiving"], legal=True),
    _d("undertaking-agreement", "Undertaking Agreement", "agreements",
       "A written undertaking to do or not do something.",
       "declaration",
       ["contact:Undertaker:undertaker", "recipient:Addressed To:", "message:Undertaking:"],
       "I, {undertaker_full_name}, hereby give the following undertaking.",
       sign_roles=["Undertaker"], legal=True),

    # ---------------------------------------------  OWNERSHIP & TRANSFER
    _d("change-of-ownership-letter", "Change of Ownership Letter", "ownership",
       "Notify a party that ownership of an item has changed hands.",
       "letter",
       ["contact:Sender:", "recipient:Recipient:", "transfer::", "message::"],
       "I am writing to notify you of a change of ownership as described below.",
       "Yours faithfully,", legal=True, keywords="transfer sale"),
    _d("vehicle-change-of-ownership", "Vehicle Change of Ownership", "ownership",
       "Transfer ownership of a car, bus or truck.",
       "agreement",
       ["person:Seller / Current Owner:seller", "person:Buyer / New Owner:buyer",
        "vehicle:Vehicle Details:vehicle", "transfer::", "notes::",
        "witnesses::", "document_date::"],
       sign_roles=["Seller / Current Owner", "Buyer / New Owner"], legal=True,
       keywords="car transfer ownership"),
    _d("motorcycle-change-of-ownership", "Motorcycle Change of Ownership", "ownership",
       "Transfer ownership of a motorcycle or okada.",
       "agreement",
       ["person:Seller / Current Owner:seller", "person:Buyer / New Owner:buyer",
        "vehicle:Motorcycle Details:motorcycle", "transfer::", "notes::",
        "witnesses::", "document_date::"],
       sign_roles=["Seller / Current Owner", "Buyer / New Owner"], legal=True,
       keywords="bike okada motorcycle transfer ownership"),
    _d("car-sale-transfer-agreement", "Car Sale & Transfer Agreement", "ownership",
       "Full sale and transfer agreement for a car.",
       "agreement",
       ["person:Seller:seller", "person:Buyer:buyer", "vehicle:Vehicle Details:vehicle",
        "sale::", "notes::", "witnesses::", "document_date::"],
       sign_roles=["Seller", "Buyer"], legal=True, keywords="car sale transfer"),
    _d("motorcycle-sale-transfer-agreement", "Motorcycle Sale & Transfer Agreement",
       "ownership",
       "Full sale and transfer agreement for a motorcycle.",
       "agreement",
       ["person:Seller:seller", "person:Buyer:buyer",
        "vehicle:Motorcycle Details:motorcycle", "sale::", "notes::",
        "witnesses::", "document_date::"],
       sign_roles=["Seller", "Buyer"], legal=True,
       keywords="bike okada motorcycle sale transfer"),
    _d("property-transfer-agreement", "Property Transfer Agreement", "ownership",
       "Agreement transferring land or property between parties.",
       "agreement",
       ["person:Transferor:transferor", "person:Transferee:transferee",
        "property::", "sale::", "notes::", "witnesses::", "document_date::"],
       sign_roles=["Transferor", "Transferee"], legal=True),
    _d("business-ownership-transfer", "Business Ownership Transfer", "ownership",
       "Transfer ownership of a business from one party to another.",
       "agreement",
       ["person:Current Owner:current_owner", "person:New Owner:new_owner",
        "asset:Business / Assets:", "sale::", "notes::", "witnesses::",
        "document_date::"],
       sign_roles=["Current Owner", "New Owner"], legal=True),
    _d("transfer-of-ownership-declaration", "Transfer of Ownership Declaration",
       "ownership",
       "Declare that ownership of an item has been transferred.",
       "declaration",
       ["contact:Declarant:", "transfer::", "witnesses::", "document_date::"],
       "I, {declarant_full_name}, hereby declare that the item described below "
       "has been transferred as stated.",
       sign_roles=["Declarant"], legal=True),
    _d("ownership-transfer-authorization", "Ownership Transfer Authorization",
       "ownership",
       "Authorize a named person to complete an ownership transfer.",
       "letter",
       ["contact:Authorizing Person:authorizing_person", "authorization::",
        "transfer::", "notes::"],
       "I, {authorizing_person_full_name}, hereby authorize the person named "
       "below to complete the ownership transfer described here.",
       "Yours faithfully,", legal=True, keywords="authority"),
    _d("asset-handover-agreement", "Asset Handover Agreement", "ownership",
       "Hand over company or personal assets with a written record.",
       "agreement",
       ["person:Handing Over:from_party", "person:Receiving:to_party",
        "asset::", "notes::", "witnesses::", "document_date::"],
       sign_roles=["Handing Over", "Receiving"], legal=True),
    _d("vehicle-handover-agreement", "Vehicle Handover Agreement", "ownership",
       "Record the handover of a vehicle to a driver, buyer or partner.",
       "agreement",
       ["person:Handing Over:from_party", "person:Receiving:to_party",
        "vehicle:Vehicle Details:vehicle", "notes::", "witnesses::",
        "document_date::"],
       sign_roles=["Handing Over", "Receiving"], legal=True),
    _d("motorcycle-handover-agreement", "Motorcycle Handover Agreement", "ownership",
       "Record the handover of a motorcycle or okada.",
       "agreement",
       ["person:Handing Over:from_party", "person:Receiving:to_party",
        "vehicle:Motorcycle Details:motorcycle", "notes::", "witnesses::",
        "document_date::"],
       sign_roles=["Handing Over", "Receiving"], legal=True,
       keywords="bike okada"),
    _d("proof-of-sale", "Proof of Sale / Sale Receipt", "ownership",
       "A receipt proving an item was sold and paid for.",
       "agreement",
       ["person:Seller:seller", "person:Buyer:buyer", "asset::", "sale::",
        "witnesses::", "document_date::"],
       sign_roles=["Seller", "Buyer"], legal=True, keywords="receipt sold"),

    # ------------------------------------------  EMPLOYMENT & WORKPLACE
    _d("job-application-letter", "Job Application Letter", "employment",
       "Apply for an advertised or known job opening.",
       "letter",
       ["contact:Applicant:", "job_target::", "application_body::"],
       "I am writing to apply for the position of {position} at {company_name}.",
       "Yours faithfully,", "Dear Hiring Manager", keywords="job work"),
    _d("employment-cover-letter", "Cover Letter", "employment",
       "Introduce your CV for an employment application.",
       "letter",
       ["contact:Applicant:", "job_target::", "application_body::"],
       "Please accept this letter as a cover for my application for the "
       "position of {position} at {company_name}.",
       "Yours sincerely,", "Dear Hiring Manager"),
    _d("job-offer-letter", "Job Offer Letter", "employment",
       "Offer a candidate a position with your organisation.",
       "letter",
       ["recipient:Candidate:", "employment:Offer Details:", "message:Terms:"],
       "Following your interview, we are pleased to offer you employment as "
       "stated below.",
       "Yours faithfully,", "Dear Candidate"),
    _d("employment-offer-letter", "Employment Offer Letter", "employment",
       "Formal employment offer with position and start date.",
       "letter",
       ["recipient:Candidate:", "employment:Offer Details:", "message:Terms:"],
       "We are pleased to offer you employment on the terms stated below.",
       "Yours faithfully,", "Dear Candidate"),
    _d("appointment-letter", "Appointment Letter", "employment",
       "Confirm the appointment of a person to a position.",
       "letter",
       ["recipient:Appointee:", "employment:Appointment Details:", "message:Terms:"],
       "We are pleased to confirm your appointment as stated below.",
       "Yours faithfully,", "Dear Appointee"),
    _d("employment-confirmation-letter", "Employment Confirmation Letter",
       "employment",
       "Confirm an employee after a probation period.",
       "letter",
       ["recipient:Employee:", "employment:Employment Details:", "message:Message:"],
       "We are pleased to confirm your employment as detailed below.",
       "Yours faithfully,", "Dear Employee"),
    _d("promotion-letter", "Promotion Letter", "employment",
       "Announce an employee's promotion to a new position.",
       "letter",
       ["recipient:Employee:", "employment:New Position Details:", "message:Message:"],
       "Congratulations - we are pleased to promote you as stated below.",
       "Yours faithfully,", "Dear Employee"),
    _d("transfer-letter", "Transfer Letter", "employment",
       "Transfer an employee to another branch, office or role.",
       "letter",
       ["recipient:Employee:", "employment:Transfer Details:", "message:Message:"],
       "This letter confirms your transfer as detailed below.",
       "Yours faithfully,", "Dear Employee"),
    _d("salary-increase-letter", "Salary Increase Letter", "employment",
       "Notify an employee of a salary review or raise.",
       "letter",
       ["recipient:Employee:", "employment:Salary Details:", "message:Message:"],
       "We are pleased to inform you that your salary has been reviewed as "
       "stated below.",
       "Yours faithfully,", "Dear Employee"),
    _d("resignation-letter", "Resignation Letter", "employment",
       "Resign formally from your position with notice.",
       "letter",
       ["contact:Employee:", "resignation::"],
       "I hereby resign from my position as {position} at {company_name}.",
       "Yours faithfully,", "Dear Sir/Madam", keywords="quit job leave work"),
    _d("retirement-letter", "Retirement Letter", "employment",
       "Announce retirement and a planned last day of service.",
       "letter",
       ["contact:Employee:", "resignation::"],
       "I write to formally notify you of my intention to retire from my "
       "position as {position} at {company_name}.",
       "Yours faithfully,", "Dear Sir/Madam"),
    _d("termination-letter", "Termination Letter", "employment",
       "End an employment or contract with formal notice.",
       "letter",
       ["recipient:Employee:", "employment:Position Details:", "message:Reason & Terms:"],
       "This letter serves as formal notice of termination as detailed below.",
       "Yours faithfully,", "Dear Employee", legal=True),
    _d("warning-letter", "Warning Letter", "employment",
       "Issue a formal warning about conduct or performance.",
       "letter",
       ["recipient:Employee:", "employment:Position Details:", "message:Warning Details:"],
       "This letter serves as a formal warning as detailed below.",
       "Yours faithfully,", "Dear Employee"),
    _d("leave-request-letter", "Leave Request Letter", "employment",
       "Request annual, sick or personal leave.",
       "letter",
       ["contact:Employee:", "employment:Position Details:",
        "message:Leave Details:"],
       "I write to request leave as detailed below.",
       "Yours faithfully,", "Dear Sir/Madam"),
    _d("leave-approval-letter", "Leave Approval Letter", "employment",
       "Approve an employee's leave request.",
       "letter",
       ["recipient:Employee:", "employment:Leave Details:", "message:Message:"],
       "Your leave request is approved as detailed below.",
       "Yours faithfully,", "Dear Employee"),
    _d("experience-letter", "Experience Letter", "employment",
       "Certify a person's work experience with your organisation.",
       "letter",
       ["recipient:Employee:", "employment:Employment Details:",
        "message:Duties & Conduct:"],
       "This is to certify that the person named below worked with us as "
       "stated.",
       "Yours faithfully,", "To Whom It May Concern", keywords="certificate"),
    _d("employment-verification-letter", "Employment Verification Letter",
       "employment",
       "Verify that someone works (or worked) with your organisation.",
       "letter",
       ["recipient:Employee:", "employment:Employment Details:", "message:Message:"],
       "This letter confirms the employment details stated below.",
       "Yours faithfully,", "To Whom It May Concern"),
    _d("recommendation-letter-employment", "Recommendation Letter", "employment",
       "Recommend a current or former employee.",
       "letter",
       ["contact:Referee:", "recipient:Recipient:",
        "message:Recommendation:"],
       "I write to recommend the employee described below without reservation.",
       "Yours faithfully,", "To Whom It May Concern", keywords="reference"),

    # --------------------------------  LEGAL / DECLARATION / AUTHORIZATION
    _d("declaration-letter", "Declaration Letter", "legal",
       "Formally declare a fact or set of facts.",
       "declaration",
       ["contact:Declarant:", "message:Facts Declared:", "witnesses::",
        "document_date::"],
       "I, {declarant_full_name}, hereby solemnly declare as follows.",
       sign_roles=["Declarant"], legal=True),
    _d("sworn-statement", "Sworn Statement", "legal",
       "A statement of fact, sworn before an authority where required.",
       "declaration",
       ["contact:Declarant:", "message:Statement:", "witnesses::",
        "document_date::"],
       "I, {declarant_full_name}, make this statement solemnly and in good "
       "faith, affirming that the contents below are true.",
       sign_roles=["Declarant"], legal=True),
    _d("affidavit-style-document", "Affidavit-Style Document", "legal",
       "An affidavit-style written statement for stamping before a "
       "commissioner of oaths.",
       "declaration",
       ["contact:Deponent:", "message:Facts Stated:", "witnesses::",
        "document_date::"],
       "I, {deponent_full_name}, of the address shown below, do hereby make "
       "oath and state as follows.",
       sign_roles=["Deponent"], legal=True),
    _d("consent-letter", "Consent Letter", "legal",
       "Give formal consent or permission for an activity.",
       "declaration",
       ["contact:Person Giving Consent:person_giving_consent", "consent::",
        "witnesses::", "document_date::"],
       "I, {person_giving_consent_full_name}, hereby give my consent as "
       "described below.",
       sign_roles=["Person Giving Consent"], legal=True, keywords="permission"),
    _d("authorization-letter", "Authorization Letter", "legal",
       "Authorize another person to act or collect on your behalf.",
       "letter",
       ["contact:Authorizing Person:authorizing_person", "authorization::",
        "notes::"],
       "I, {authorizing_person_full_name}, hereby authorize the person named "
       "below to act on my behalf as described.",
       "Yours faithfully,", legal=True, keywords="authority act behalf"),
    _d("letter-of-indemnity", "Letter of Indemnity", "legal",
       "Undertake to compensate another party for specified loss.",
       "declaration",
       ["contact:Indemnifier:", "recipient:Indemnified Party:", "message:Indemnity Terms:"],
       "I, {indemnifier_full_name}, hereby indemnify the party named below on "
       "the terms stated.",
       sign_roles=["Indemnifier"], legal=True),
    _d("power-of-attorney", "Power of Attorney", "legal",
       "Appoint someone as your attorney to act for you. Stamp/notarise "
       "before use.",
       "declaration",
       ["contact:Donor / Principal:donor_principal", "person:Attorney:attorney",
        "authorization:Powers Granted:", "witnesses::", "document_date::"],
       "I, {donor_principal_full_name}, hereby appoint {attorney_full_name} "
       "as my attorney to do the acts described below on my behalf.",
       sign_roles=["Donor / Principal", "Attorney"], legal=True,
       keywords="poa attorney"),
    _d("undertaking-letter", "Undertaking Letter", "legal",
       "Give a written promise to do or stop doing something.",
       "declaration",
       ["contact:Undertaker:", "recipient:Addressed To:", "message:Undertaking:"],
       "I, {undertaker_full_name}, hereby give the following undertaking.",
       sign_roles=["Undertaker"], legal=True),
    _d("no-objection-letter", "No Objection Letter", "legal",
       "State that you have no objection to a proposed action.",
       "letter",
       ["contact:Issuer:", "recipient:Addressed To:", "message:Subject & Details:"],
       "I, {issuer_full_name}, write to state that I have no objection to the "
       "matter described below.",
       "Yours faithfully,", legal=True, keywords="noc no objection"),
    _d("statutory-declaration", "Statutory Declaration", "legal",
       "A formal declaration for statutory purposes. May require "
       "commissioning.",
       "declaration",
       ["contact:Declarant:", "message:Matter Declared:", "witnesses::",
        "document_date::"],
       "I, {declarant_full_name}, do solemnly and sincerely declare as follows.",
       sign_roles=["Declarant"], legal=True),

    # ------------------------------------------------  SCHOOL & ACADEMIC
    _d("admission-letter", "Admission Letter", "school",
       "Offer admission to a student or applicant.",
       "letter",
       ["recipient:Applicant:", "admission::", "message:Requirements:"],
       "We are pleased to offer you admission as detailed below.",
       "Yours faithfully,", "Dear Applicant"),
    _d("scholarship-application-letter", "Scholarship Application Letter",
       "school",
       "Apply for a scholarship or bursary.",
       "letter",
       ["contact:Applicant:", "recipient:Scholarship Committee:",
        "school:Studies:", "message:Why I Qualify:"],
       "I am writing to apply for the scholarship described below.",
       "Yours faithfully,", "Dear Committee"),
    _d("school-transfer-letter", "School Transfer Letter", "school",
       "Request a transfer of a student to another school.",
       "letter",
       ["contact:Parent / Guardian:guardian", "recipient:Principal:",
        "school:Student Details:", "message:Reason & Request:"],
       "I write to request the transfer of the student named below.",
       "Yours faithfully,", "Dear Sir/Madam"),
    _d("withdrawal-letter", "Withdrawal Letter", "school",
       "Withdraw a student from a school or programme.",
       "letter",
       ["contact:Parent / Guardian:guardian", "recipient:Principal:",
        "school:Student Details:", "message:Message:"],
       "I write to formally withdraw the student named below.",
       "Yours faithfully,", "Dear Sir/Madam"),
    _d("permission-letter", "Permission Letter", "school",
       "Request permission for a student activity or absence.",
       "letter",
       ["contact:Parent / Guardian:guardian", "recipient:Principal:",
        "consent::", "message:Message:"],
       "I write to request permission as described below.",
       "Yours faithfully,", "Dear Sir/Madam"),
    _d("recommendation-letter-school", "Recommendation Letter", "school",
       "Recommend a student for admission or an award.",
       "letter",
       ["contact:Referee:", "recipient:Recipient:",
        "school:Student Details:", "message:Recommendation:"],
       "I write to recommend the student described below without reservation.",
       "Yours faithfully,", "Dear Sir/Madam", keywords="reference"),
    _d("student-reference-letter", "Student Reference Letter", "school",
       "Provide a factual reference for a student.",
       "letter",
       ["contact:Referee:", "recipient:Recipient:",
        "school:Student Details:", "message:Reference Details:"],
       "This letter serves as a reference for the student named below.",
       "Yours faithfully,", "To Whom It May Concern"),
    _d("apology-letter-school", "Apology Letter", "school",
       "Apologise formally for an incident or absence.",
       "letter",
       ["contact:Sender:", "recipient:Recipient:", "message:Apology:"],
       "I write to sincerely apologise for the matter described below.",
       "Yours faithfully,", "Dear Sir/Madam"),
    _d("request-for-transcript-letter", "Request for Transcript Letter", "school",
       "Request an academic transcript or records.",
       "letter",
       ["contact:Requester:", "recipient:Registrar:", "school:Student Details:",
        "message:Message:"],
       "I write to request the academic transcript of the student named below.",
       "Yours faithfully,", "Dear Sir/Madam", keywords="records result"),

    # ------------------------------------------------  PERSONAL & GENERAL
    _d("apology-letter-personal", "Apology Letter", "personal",
       "Say sorry sincerely, in writing.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Apology:"],
       "I write to sincerely apologise for what happened.",
       "Yours sincerely,"),
    _d("thank-you-letter", "Thank You Letter", "personal",
       "Thank someone for their kindness, gift or support.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "I write to express my heartfelt thanks.",
       "Yours sincerely,", keywords="gratitude appreciation"),
    _d("congratulations-letter", "Congratulations Letter", "personal",
       "Congratulate someone on an achievement or milestone.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "Congratulations on the wonderful achievement described below.",
       "Yours sincerely,"),
    _d("condolence-letter", "Condolence Letter", "personal",
       "Comfort someone bereaved with a written tribute.",
       "letter", ["contact:Sender:", "recipient:Recipient:", "message:Message:"],
       "I was deeply saddened to learn of your loss. Please accept my "
       "heartfelt condolences.",
       "Yours sincerely,", "Dear Friend"),
    _d("invitation-letter-personal", "Invitation Letter", "personal",
       "Invite family or friends to a ceremony or event.",
       "letter",
       ["contact:Host:", "recipient:Guest:", "message:Event Details:"],
       "We are delighted to invite you as detailed below.",
       "Yours sincerely,"),
    _d("sponsorship-letter", "Sponsorship Letter", "personal",
       "Request sponsorship for a person, team or cause.",
       "letter",
       ["contact:Requester:", "recipient:Potential Sponsor:", "message:Request Details:"],
       "I write to respectfully request your sponsorship as described below.",
       "Yours faithfully,", "Dear Sir/Madam"),
    _d("financial-support-letter", "Financial Support Letter", "personal",
       "Request financial assistance and explain the need.",
       "letter",
       ["contact:Requester:", "recipient:Recipient:", "message:Request Details:"],
       "I write to request your kind financial support as described below.",
       "Yours faithfully,", "Dear Sir/Madam"),
    _d("character-reference-letter", "Character Reference Letter", "personal",
       "Vouch for someone's character from personal knowledge.",
       "letter",
       ["contact:Referee:", "recipient:Recipient:",
        "message:Character & Qualities:"],
       "I have known the person described below for some time and write to "
       "vouch for their character.",
       "Yours faithfully,", "To Whom It May Concern", keywords="reference"),
    _d("personal-recommendation-letter", "Personal Recommendation Letter",
       "personal",
       "Recommend someone you know personally for an opportunity.",
       "letter",
       ["contact:Referee:", "recipient:Recipient:", "message:Recommendation:"],
       "I write to personally recommend the person described below.",
       "Yours faithfully,", "To Whom It May Concern", keywords="reference"),
]

DOC_TYPES_BY_SLUG = {d["slug"]: d for d in DOC_TYPES}
DOCS_BY_CATEGORY: dict[str, list[dict[str, Any]]] = {}
for _doc in DOC_TYPES:
    DOCS_BY_CATEGORY.setdefault(_doc["category"], []).append(_doc)


def get_doc(slug: str) -> dict[str, Any] | None:
    return DOC_TYPES_BY_SLUG.get(slug)


def search_docs(query: str) -> list[dict[str, Any]]:
    """Match a query against name, description, keywords and category."""
    q = (query or "").strip().lower()
    if not q:
        return []
    out = []
    for doc in DOC_TYPES:
        cat = CATEGORIES_BY_SLUG[doc["category"]]["name"]
        haystack = f"{doc['name']} {doc['desc']} {doc['keywords']} {cat}".lower()
        if all(term in haystack for term in q.split()):
            out.append(doc)
    return out


def field_instances(doc: dict[str, Any]) -> list[dict[str, Any]]:
    """
    Expand a doc's group tokens into concrete field lists.

    Each instance: {key, group, role, prefix, fields: [{name,label,type,...}]}
    Field name is 'prefix_fieldname' (or bare 'fieldname' when no prefix);
    label is 'Role FieldLabel' when a role is given.
    """
    instances: list[dict[str, Any]] = []
    for token in doc["groups"]:
        parts = token.split(":")
        group_key = parts[0]
        role = parts[1] if len(parts) > 1 and parts[1] else ""
        prefix = parts[2] if len(parts) > 2 and parts[2] else ""
        if not prefix and role:
            prefix = role.split(" ")[0].split("/")[0].lower()
        fields = []
        for field_name in GROUP_FIELDS[group_key]:
            fdef = FIELD_DEFS[field_name]
            label = f"{role} {fdef['label']}" if role else fdef["label"]
            fields.append({
                "name": f"{prefix}_{field_name}" if prefix else field_name,
                "label": label,
                "type": fdef["type"],
                "placeholder": fdef.get("placeholder", ""),
                "inputmode": fdef.get("inputmode", ""),
            })
        heading = role or group_key.replace("_", " ").title()
        if heading == "Document Date":
            heading = "Date"
        instances.append({
            "key": prefix or group_key,
            "group": group_key,
            "role": role,
            "heading": heading,
            "fields": fields,
        })
    return instances


ALL_FIELDS_CACHE: dict[str, list[dict[str, Any]]] = {}


def fields_for(slug: str) -> list[dict[str, Any]]:
    doc = get_doc(slug)
    if doc is None:
        return []
    if slug not in ALL_FIELDS_CACHE:
        ALL_FIELDS_CACHE[slug] = field_instances(doc)
    return ALL_FIELDS_CACHE[slug]


def flat_fields(doc: dict[str, Any]) -> list[dict[str, Any]]:
    """All concrete fields of a doc, flattened (for form parsing)."""
    return [f for inst in field_instances(doc) for f in inst["fields"]]
